use serde::{Deserialize, Serialize};
use sqlx::prelude::FromRow;
use utoipa::{IntoParams, ToSchema};

use crate::sql::{get_search_where_condition, get_sort_col_str, get_sorter_str};

#[derive(Debug, Serialize, Deserialize, ToSchema, FromRow)]
pub struct Area {
    /// Id will generated by the system.
    #[serde(default)]
    pub id: i64,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub description: String,
    pub color: Option<String>,
    pub text_color: Option<String>,
}

#[derive(Debug, Default, Deserialize, ToSchema, IntoParams)]
pub struct GetAreasQuery {
    pub id: Option<i64>,
    pub name: Option<String>,
    pub sorters: Option<Vec<String>>,
}

impl GetAreasQuery {
    pub fn get_where_condition(&self) -> String {
        let mut conditions = Vec::with_capacity(1);
        if let Some(v) = &self.id {
            conditions.push(format!("areas.id = {v}"));
        }
        if let Some(v) = &self.name {
            conditions.push(get_search_where_condition("areas.name", v));
        }

        if !conditions.is_empty() {
            let c = conditions.join(" AND ");
            format!("WHERE {c}").into()
        } else {
            "".into()
        }
    }

    pub fn get_order_condition(&self) -> String {
        let mut conditions = vec![];
        if self.name.is_some() {
            conditions.push("length(areas.name) ASC".into());
        }
        if let Some(sorters) = self.sorters.as_ref() {
            for sorter in sorters {
                let mut col = get_sort_col_str(sorter);
                let sort = get_sorter_str(sorter);
                col = format!("areas.{col} {sort}");

                conditions.push(col);
            }
        }
        if !conditions.is_empty() {
            let c = conditions.join(", ");
            format!("ORDER BY {c}").into()
        } else {
            "".into()
        }
    }
}
