use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use utoipa::{IntoParams, ToSchema};

use crate::sql::{get_search_where_condition, get_sort_col_str, get_sorter_str};

#[derive(Debug, Serialize, Deserialize, ToSchema, FromRow)]
pub struct Warehouse {
    /// Id will generated by the system.
    #[serde(default)]
    pub id: i64,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub person_in_charge_id: i64,
    #[serde(default)]
    pub area_id: i64,
    #[serde(default)]
    pub address: String,
    pub color: Option<String>,
    pub text_color: Option<String>,
}

#[derive(Debug, Deserialize, ToSchema, IntoParams)]
pub struct GetWarehousesQuery {
    pub id: Option<i64>,
    pub name: Option<String>,
    pub person_in_charge_id: Option<i64>,
    pub area_id: Option<i64>,
    pub address: Option<String>,
    pub sorters: Option<Vec<String>>,
}

#[derive(Debug, Serialize, Deserialize, ToSchema, FromRow)]
pub struct WarehouseToLinkQuery {
    pub user_id: i64,
}

impl GetWarehousesQuery {
    pub fn get_where_condition(&self) -> String {
        let mut conditions = Vec::with_capacity(3);
        if let Some(v) = &self.id {
            conditions.push(format!("warehouses.id = {v}").into());
        }
        if let Some(v) = &self.name {
            let v = v.trim();
            conditions.push(get_search_where_condition("warehouses.name", v));
        }
        if let Some(v) = &self.person_in_charge_id {
            conditions.push(format!("warehouses.person_in_charge_id={v}").into());
        }
        if let Some(v) = &self.area_id {
            conditions.push(format!("warehouses.area_id={v}").into());
        }
        if let Some(v) = &self.address {
            let v = v.trim();
            conditions.push(format!("warehouses.address LIKE '%{v}%'").into());
        }
        if !conditions.is_empty() {
            let c = conditions.join(" AND ");
            format!("WHERE {c}").into()
        } else {
            "".into()
        }
    }

    pub fn get_order_condition(&self) -> String {
        let mut conditions = vec![];
        if self.name.is_some() {
            conditions.push("length(warehouses.name) ASC".into());
        }
        if let Some(sorters) = self.sorters.as_ref() {
            for sorter in sorters {
                let mut col = get_sort_col_str(sorter);
                let sort = get_sorter_str(sorter);
                if col == "person_in_charge_id" {
                    col = format!("person_in_charge_name {sort}").into();
                } else if col == "area_id" {
                    col = format!("area_name {sort}").into();
                } else {
                    col = format!("warehouses.{col} {sort}").into();
                }
                conditions.push(col)
            }
        }

        if !conditions.is_empty() {
            let c = conditions.join(", ");
            format!("ORDER BY {c}").into()
        } else {
            "".into()
        }
    }
}
